### PR TITLE
Add Adulttime Interactive Downloader

### PR DESCRIPTION
**Pull request by tooliload**
This Addons allowed to get Interactive Toy-Downloads from Adulttime Scene

### CODE REVIEW

**Comment by Tetrax-10** [comment]
We appreciate your contribution. Please note that CommunityScripts now adheres to strict formatting guidelines. Kindly refer to the [Contributing guide](https://github.com/stashapp/CommunityScripts?tab=readme-ov-file#contributing) for instructions.

**Comment by Tetrax-10** [comment]
### It didn't work for me. I added this [scene](https://stashdb.org/scenes/0db12fbf-9db7-404c-babc-3805a460c406) but it says this.

image

Screenshot 2024-02-17 222409

### Can you please explain what it downloads with some screenshot?

**Comment by tooliload** [comment]
Please check if there is a valid Link on Scene. Can you please check?

**Comment by Tetrax-10** [comment]
image

There is one

**Comment by tooliload** [comment]
Thank you. I will update the Plug in. At the moment, there are only compatible with adulttime.com URLs

**Comment by Tetrax-10** [comment]
after you update kindly give me a test scene so I can check and test it.

**Comment by Tetrax-10** [comment]
Can you give me an example sene to test?

**Comment by tooliload** [comment]
Example, first Link with https://stashdb.org/scenes/ebd6125c-e6e2-4651-a826-ac4cf1f7fa29

**Comment by DogmaDragon** [comment]
@tooliload can you verify this works with the latest Stash release?

**Comment by tooliload** [comment]
Tested in v0.26.1 successfully

**Pull request merged**
