### PR TITLE
Added Plex Better Styles CSS

### PR DESCRIPTION
**Pull request by elkorol**
Added Plex Better Styles CSS Theme

### CODE REVIEW

**Comment by Tetrax-10** [comment]
Check out #259.

**Comment by elkorol** [comment]
Ah that's even better. Cool man. What about the various other CSS snippets should they be left hardcoded since they aren't that big or should they have their own plugins?

**Comment by Tetrax-10** [comment]
Currently I have managed to dynamically required css files when the option is enabled.

**Comment by Tetrax-10** [comment]
#259 includes Plex Better Styles theme

**Pull request closed without merging**
