### PR TITLE
added youtube-dl url setter to community scripts with update to use y…

### PR DESCRIPTION
**Pull request by skier233**

### CODE REVIEW

**Comment by scruffynerf** [comment]
Not crazy about the full dump of Niemands old repo right into the community repo like this.  So let's leave this open for now, and plan on doing it the right way (with rewrites, as that repo is a bit 'messy' in terms of layout.  The code needs review anyway, the Bulk URL scraper is on my todo list to rewrite first as well.

**Comment by skier233** [comment]
Thats fine. this at least gets the working code somewhere where people can see it

**Comment by scruffynerf** [comment]
I did some very extensive rewrites of the main concept of this, but improved a lot of the workflow and usefulness of it. Including batch downloading and improved json handling, so I'll get my revamp into the main repo and we can close this once I do.  It's currently at 

https://github.com/scruffynerf/stashtoolkits/tree/main/AcquisitionToolKit/plugins/YTDLP

This also includes all of the bits of Niemand's repo, so hopefully I'll either clean up or include those in a different PR

**Comment by scruffynerf** [comment]
I'll figure out if the YTDLP downloader is going to live in the official repo (I'll discuss concerns in Discord), but either way, we can close this for now.

**Pull request closed without merging**
