### PR TITLE
Gallery DateParser - Parse dates from filenames & path for galleries

### PR DESCRIPTION
**Pull request by HijackHornet**
Simple plugin that add a new task allowing you to scan galleries without a date and try to find the date from its path (inclusing filename).
Example working date : 
Oct. 15, 2002
15 October 2022
15/10/2022
15/10/22
15-10-2022
etc

Require stashapi and dateParser. Requirement.txt included

### CODE REVIEW

**Comment by Kallaide** [comment]
Getting the following errors in the log when attempting to run Date Parser:

2023-01-02 13:59:18    Error    Plugin returned error: exit status 1
2023-01-02 13:59:18    Error    [Plugin / Date Parser] SyntaxError: invalid syntax
2023-01-02 13:59:18    Error    [Plugin / Date Parser]           ^
2023-01-02 13:59:18    Error    [Plugin / Date Parser]     match mode_arg:
2023-01-02 13:59:18    Error    [Plugin / Date Parser]   File "C:\Users\Cortn\.stash\plugins\DateParser\date_parser.py", line 20

**Comment by HijackHornet** [comment]
It's because match is in python 3.10+. Please update python3 if possible:) else you can open the python script and replace the match by a series of If statements

**Comment by skinnerback** [comment]
requirements are all showing as satisfied, but I'm getting a ModuleNotFoundError for stashapi.

2023-01-13 08:22:46	Error	Plugin returned error: exit status 1
2023-01-13 08:22:46	Error	[Plugin / Date Parser] ModuleNotFoundError: No module named 'stashapi'
2023-01-13 08:22:46	Error	[Plugin / Date Parser]     import stashapi.log as log
2023-01-13 08:22:46	Error	[Plugin / Date Parser]   File "C:\Users\username\.stash\plugins\DateParser/date_parser.py", line 4, in <module>
2023-01-13 08:22:46	Error	[Plugin / Date Parser] Traceback (most recent call last):

**Comment by HijackHornet** [comment]
> requirements are all showing as satisfied, but I'm getting a ModuleNotFoundError for stashapi.
Try and install it manually with `pip install stashapp-tools`

**Comment by skinnerback** [comment]
That did not work, but I found the issue.  I had Python 3.8.2 before installing this plugin, when I upgraded to 3.11.1 since I saw it needed 3.10+.  It seems I now have 2 versions of Python installed.  When I ran the requirements install through Command Prompt, it looks like it installed everything to 3.8.2.  

I ran:
[pathto]\Python311\python.exe -m pip install -r requirements.txt
to make everything install into Python 3.11.1 and now the plugin is working.

**Comment by HijackHornet** [comment]
Thanks for sharing the solution :) I'm having the same issue as well.
I'm updating the code to use the latest stashapi, and downgrade the python requirement so 3.10+ isnt mandatory in the future ;)

**Pull request merged**
