### PR TITLE
[renamerOnUpdate] changed the rename method

### PR DESCRIPTION
**Pull request by Belleyy**
Changed how the field was detected/changed in the template. It should solve issue #96 #79 

Need more testing, if people can test and report if this change too many thing in your template. Use Dryrun

### CODE REVIEW

**Comment by echo6ix** [comment]
Testing using my [config.zip](https://github.com/stashapp/CommunityScripts/files/10047676/config.zip) file.

`default_template = "$studio.$date.$title{.$performer}"`

$studio|$date|$title|$performer|output|expected output
---|---|---|---|---|---|
null|null|null|null|.title.mp4|...mp4
Brazzers|null|null|null|Brazzers.title.mp4|Brazzers...mp4
null|1970-01-01|null|null|.1970-01-01.title.mp4|.1970-01-01..mp4
null|null|null|Jane|error[^e1]|...Jane.mp4
Brazzers|1970-01-01|Hello|null|Brazzers.1970-01-01.Hello.mp4|✔️
Brazzers|1970-01-01|Hello|Jane|error[^e1]|Brazzers.1970-01-01.Hello.Jane.mp4

When enabling the following:
```
field_replacer = {
    "$studio": {"replace": ".", "with": ""},
    "$title": {"replace": ".", "with": ""},
    "$performer":  {"replace": ".", "with": ""}
}
```
Periods are correctly stripped from the field elements only! ✔️

[^e1]:ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate] main function error: '40'
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate] Traceback (most recent call last):
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1293, in <module>
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1052, in renamer
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]     scene_information = extract_info(stash_scene, template)
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 506, in extract_info
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate]     perf_rating[str(perf['rating'])].append(perf['name'])
ERRO[2022-11-19 13:07:16] [Plugin / renamerOnUpdate] KeyError: '40'

**Comment by echo6ix** [comment]
Same config file, no changes.

Any iteration causes an error.

```
INFO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate] Dry mode on
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate] main function error: replace() argument 2 must be str, not None
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate] Traceback (most recent call last):
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1297, in <module>
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1067, in renamer
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]     scene_information['new_directory'] = create_new_path(scene_information, template)
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 781, in create_new_path
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]     path_list.append(re.sub('[\\/:"*?<>|]+', '', makePath(scene_info, part)).strip())
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]   File "/home/username/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 725, in makePath
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate]     r = r.replace("$title", t)
ERRO[2022-11-19 15:57:45] [Plugin / renamerOnUpdate] TypeError: replace() argument 2 must be str, not None
```

**Comment by echo6ix** [comment]
It's looking good so far with the last fix. No issues detected yet with my config👍

**Comment by fidofido300** [comment]
I am getting the following Error
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate] KeyError: '100'
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]     perf_rating[str(perf['rating'])].append(perf['name'])
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]   File "plugins\renamerOnUpdate/renamerOnUpdate.py", line 506, in extract_info
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]     scene_information = extract_info(stash_scene, template)
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]   File "plugins\renamerOnUpdate/renamerOnUpdate.py", line 1056, in renamer
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate]   File "plugins\renamerOnUpdate/renamerOnUpdate.py", line 1297, in <module>
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate] Traceback (most recent call last):
2022-11-20 09:55:14
Error   
[Plugin / renamerOnUpdate] main function error: '100'

**Pull request merged**
